### ISSUE TITLE
Fix Infinite Scroll

### ISSUE THREAD

**Issue by lcrojano** [lcrojano/Giphy_Explorer#13]
Scroll is implemented but, in some windows sizes, this doesn't activate.

https://github.com/lcrojano/Giphy_Explorer/blob/68e184948969a10b069d37740f30acb6188ff09b/scripts/scripts.js#L164

**Comment by nayangoyal** [comment]
Hi, @lcrojano can you assign this issue to me? I want to work on this issue.

**Comment by lcrojano** [comment]
> Hi, @lcrojano can you assign this issue to me? I want to work on this issue.

Sure, feel free to ask any question

**Comment by saurabhbakolia** [comment]
Hey, can you tell me what exactly issue you are facing. I can work on it.
