### ISSUE TITLE
Implement back to top buttom

### ISSUE THREAD

**Issue by lcrojano** [lcrojano/Giphy_Explorer#15]
Add a back-to-top button

![image](https://github.com/lcrojano/Giphy_Explorer/assets/5177737/a41f6e83-fd8a-49db-bc45-77e25d8b555c)

**Comment by OkenHaha** [comment]
Hello, I can work on this. Can you please assign this to me?

**Comment by lcrojano** [comment]
Hey, could you please send the pull request again? But before doing so, make sure to synchronize your fork.

**Comment by OkenHaha** [comment]
@lcrojano I've synchronize my fork and made a pull request. Please look into it and see if it conflicts with the merge.

**Comment by lcrojano** [comment]
closed with #19
