### ISSUE TITLE
[Feature]: Make the Search Bar sticky to from top .

### ISSUE THREAD

**Issue by veerendra19codes** [lcrojano/Giphy_Explorer#20]
Hey @lcrojano your project is wonderful, however I would like to  make the Search bar sticky from top ,so that user can search while he has scrolled down for better UI and user experience. Please assign this issue to me I would like to work on this.

**Screenshots/Recordings**
*issue*

https://github.com/lcrojano/Giphy_Explorer/assets/113845853/2934bb85-0b30-4061-afe8-3914550f90ea

Assign!!

**Comment by lcrojano** [comment]
Thanks for the suggestion, @veerendra19codes! I agree that making the search bar sticky would improve the user experience. I'm happy to assign this issue to you. Please let me know if you have any questions or need any help.
I'm looking forward to seeing your pull request!

**Comment by veerendra19codes** [comment]
Thank you for assigning !🙌
