### ISSUE TITLE
Github Button

### ISSUE THREAD

**Issue by lcrojano** [lcrojano/Giphy_Explorer#26]
Please add a GitHub button at the top right corner of the page.

**Comment by capedCrusaderr** [comment]
hey there is anyone working on this issue , I would like to try my hands on ?

**Comment by capedCrusaderr** [comment]
hi @lcrojano , just checked out the website and wanted to ask that do I have to add GitHub button beside the search ?

**Comment by lcrojano** [comment]
It could be fixed at the top right corner.
![image](https://github.com/lcrojano/Giphy_Explorer/assets/5177737/95252b47-2990-428d-9a14-4c11ffa06f22)

**Comment by r0ld3x** [comment]
@lcrojano  assign me

**Comment by capedCrusaderr** [comment]
> It could be fixed at the top right corner.
> 
> ![image](https://github.com/lcrojano/Giphy_Explorer/assets/5177737/95252b47-2990-428d-9a14-4c11ffa06f22)
> 
> 

Ok @lcrojano thanks for the heads up

**Comment by capedCrusaderr** [comment]
hey @lcrojano , I added the button to the top right corner it's just that there is no space between search logo and the button. could you please guide me?

**Comment by lcrojano** [comment]
could be added here.

![image](https://github.com/lcrojano/Giphy_Explorer/assets/5177737/4f6a3d77-2118-47ee-b383-c86ef6ea45b7)

**Comment by capedCrusaderr** [comment]
any idea @lcrojano how to clear the spacing between the GitHub and log in button ? I tried using the margin property but it doesn't seem to work!
![Uploading Screenshot 2023-10-26 at 11.09.08 AM.png…]()

**Comment by capedCrusaderr** [comment]
Hey @lcrojano how to clear the space between github button and log in button , I used the margin property but it doesn't seem to work. Please help me out !![image](https://github.com/lcrojano/Giphy_Explorer/assets/113660385/cc42f982-8df7-436d-8804-586753c89173)

**Comment by r0ld3x** [comment]
On it it should be placed on top right corner or inside navbar?

**Comment by lcrojano** [comment]
@r0ld3x could you work together in this issue?

**Comment by r0ld3x** [comment]
> @r0ld3x could you work together in this issue?

Yes tell me where you want it

**Comment by r0ld3x** [comment]
> Please add a GitHub button at the top right corner of the page.

Ok got it going it right now

**Comment by lcrojano** [comment]
On it should it be placed in top right corner or inside the navbar?

Both options are correct, so choose whichever one you prefer. Let me know if you need any help.

**Comment by capedCrusaderr** [comment]
@r0ld3x would be great , if you can guide me

**Comment by r0ld3x** [comment]
> @r0ld3x would be great , if you can guide me 

I think you are completing that hacktoberfest right?

**Comment by lcrojano** [comment]
Hi @r0ld3x, could you please submit a PR with your work so that we can review it and proceed further?

**Comment by r0ld3x** [comment]
> Hi @r0ld3x, could you please submit a PR with your work so that we can review it and proceed further?

On it

**Comment by capedCrusaderr** [comment]
> > @r0ld3x would be great , if you can guide me 
> 
> I think you are completing that hacktoberfest right?

Yes plus i am new to open source so yeah☺️

**Comment by r0ld3x** [comment]
> > > @r0ld3x would be great , if you can guide me
> > 
> > 
> > I think you are completing that hacktoberfest right?
> 
> Yes plus i am new to open source so yeah☺️

how many you completed?

**Comment by capedCrusaderr** [comment]
> > > > @r0ld3x would be great , if you can guide me
> 
> > > 
> 
> > > 
> 
> > > I think you are completing that hacktoberfest right?
> 
> > 
> 
> > Yes plus i am new to open source so yeah☺️
> 
> 
> 
> how many you completed?

Would be my 1st pr but like i said my major aim is to get started

**Comment by r0ld3x** [comment]
![image](https://github.com/lcrojano/Giphy_Explorer/assets/77254818/56bc6a43-0382-429b-9292-194852e3d79e)
Is that looks good?

**Comment by r0ld3x** [comment]
> ![image](https://user-images.githubusercontent.com/77254818/278459982-56bc6a43-0382-429b-9292-194852e3d79e.png) Is that looks good?

@lcrojano

**Comment by r0ld3x** [comment]
> > > > > @r0ld3x would be great , if you can guide me
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I think you are completing that hacktoberfest right?
> > 
> > 
> > > 
> > 
> > 
> > > Yes plus i am new to open source so yeah☺️
> > 
> > 
> > how many you completed?
> 
> Would be my 1st pr but like i said my major aim is to get started

I have only 1 PR left i already completed 3

**Comment by r0ld3x** [comment]
![image](https://github.com/lcrojano/Giphy_Explorer/assets/77254818/bf63dc0e-88c7-4c20-95b5-479d96c19960)

making PR

**Comment by lcrojano** [comment]
@capedCrusaderr this repo is good to contribute: https://github.com/rupali-codes/LinksHub

**Comment by r0ld3x** [comment]
> @capedCrusaderr this repo is good to contribute: https://github.com/rupali-codes/LinksHub

You merged my pr?

**Comment by lcrojano** [comment]
Hi @capedCrusader,

I just merged PR #37, so you can start working on another issue. 

I would like you to work on issue #38. Before you start, please sync your project with the latest changes to avoid any code conflicts. 

This issue is intended to be a starting point for new contributors. Please feel free to leave any questions or comments you have about contributing to the project, and we will be happy to help.

**Comment by r0ld3x** [comment]
> Hi @CapedCrusader,
> 
> I just merged PR #37, so you can start working on another issue.
> 
> I would like you to work on issue #38. Before you start, please sync your project with the latest changes to avoid any code conflicts.
> 
> This issue is intended to be a starting point for new contributors. Please feel free to leave any questions or comments you have about contributing to the project, and we will be happy to help.

I'll start working today

**Comment by capedCrusaderr** [comment]
> Hi @capedCrusader,
> 
> 
> 
> I just merged PR #37, so you can start working on another issue. 
> 
> 
> 
> I would like you to work on issue #38. Before you start, please sync your project with the latest changes to avoid any code conflicts. 
> 
> 
> 
> This issue is intended to be a starting point for new contributors. Please feel free to leave any questions or comments you have about contributing to the project, and we will be happy to help.
> 
> 

Sure no problem and thanks @r0ld3x for helping out in the issue😇

**Comment by r0ld3x** [comment]
> > Hi @capedCrusader,
> > 
> > 
> > 
> > I just merged PR #37, so you can start working on another issue. 
> > 
> > 
> > 
> > I would like you to work on issue #38. Before you start, please sync your project with the latest changes to avoid any code conflicts. 
> > 
> > 
> > 
> > This issue is intended to be a starting point for new contributors. Please feel free to leave any questions or comments you have about contributing to the project, and we will be happy to help.
> > 
> > 
> 
> Sure no problem and thanks @r0ld3x for helping out in the issue😇 

♥️
