### ISSUE TITLE
Share modal

### ISSUE THREAD

**Issue by lcrojano** [lcrojano/Giphy_Explorer#27]
How should we go about designing a share modal for Facebook, X and other platforms? Your best approach recommendations would be appreciated.

**Comment by bharath090909** [comment]
@lcrojano can I take up on this issue ?

**Comment by bharath090909** [comment]
And can you give me more details about the issue. Should I need to create share modal from scratch ?

**Comment by lcrojano** [comment]
When a user clicks on a GIF, a modal with options to share on common social networks should appear. This could be a reference:

![image](https://github.com/lcrojano/Giphy_Explorer/assets/5177737/2b5b3a7e-60a1-4f1f-94d1-119eb51eabcf)

**Comment by bharath090909** [comment]
@lcrojano , I've finished the UI for the share modal but have been struggling with the JavaScript functionality all morning. I've attached a screenshot of the UI for your reference.
![Screenshot 2023-10-20 at 9 33 29 PM](https://github.com/lcrojano/Giphy_Explorer/assets/91081887/656442b0-8fc4-455f-bed2-7d4a68922ccd)

**Comment by bharath090909** [comment]
@lcrojano I have raised a PR please check.
