### ISSUE TITLE
Add Favorites Page

### ISSUE THREAD

**Issue by lcrojano** [lcrojano/Giphy_Explorer#29]
As per the requirement mentioned in task #28, please create a new page that displays the favorites saved in the local storage. This page should be dependent on task #28.

**Comment by CrisitoJ** [comment]
Is this still open?

**Comment by lcrojano** [comment]
Is this still open?

Feel free to ask anything you need. I'm excited to see how you can contribute.

**Comment by CrisitoJ** [comment]
https://github.com/lcrojano/Giphy_Explorer/assets/115337506/5329ff49-5ebc-4fb4-8713-d52b8da80792

**Comment by lcrojano** [comment]
Great job! You can now submit a pull request to add your contribution to the repository.
