### ISSUE TITLE
fix github image

### ISSUE THREAD

**Issue by lcrojano** [lcrojano/Giphy_Explorer#38]
## Issue Description:
The GitHub icon is not loading.

## Possible Solution
To fix this issue, you can consider one of the following solutions:

Modify the image source from src="/assets/images/github-mark-white.png" to src="assets/images/github-mark-white.png" (remove the leading '/').
or 

Update the image source to a direct path to the file, like this: [GitHub Icon](https://lcrojano.github.io/Giphy_Explorer/assets/images/github-mark-white.png). you should use "https://raw.githubusercontent.com/username/repository/branch/path/to/file"

Please make the necessary adjustments to ensure the GitHub icon loads correctly.
Screenshot
![image](https://github.com/lcrojano/Giphy_Explorer/assets/5177737/02658bef-dde0-440c-8033-9db42924676e)

This is intended to be a short issue.

**Comment by lcrojano** [comment]
@CapedCrusader

**Comment by dabhitapan** [comment]
Hi @lcrojano assign it to me

**Comment by dabhitapan** [comment]
@lcrojano  added mr here https://github.com/lcrojano/Giphy_Explorer/pull/40

**Comment by r0ld3x** [comment]
> The GitHub icon is not being loaded because it is st up as a relative path.
> 
> ## Possible Solution
> You could fix it by adding a direct path to the file: https://github.com/lcrojano/Giphy_Explorer/blob/main/assets/images/github-mark-white.png
> 
> ## Screenshot
> [![image](https://github.com/lcrojano/Giphy_Explorer/blob/3b833a8c20e074944a9c18a10c98978f063a1033/assets/images/github-mark-white.png?raw=true)](https://user-images.githubusercontent.com/5177737/278475083-b52102b6-944c-4d49-80d7-387fd5135e90.png)
> 
> @CapedCrusader

this url cant be used as a source

**Comment by dabhitapan** [comment]
Hi @r0ld3x why not?

**Comment by lcrojano** [comment]
Hi! The pull request was created to help newcomers achieve their first commit for Hacktoberfest. It was specifically created for @CapedCrusader. If we don't receive a response or if no longer interested in solving this issue within a couple of days, we will accept the first pull request.

to fix the issue you could remove the "/"

`<img src="/assets/images/github-mark-white.png" alt="GitHub">`
to
 `<img src="assets/images/github-mark-white.png" alt="GitHub">`



Also, I've created #50 so anyone can work on this new issue.

**Comment by capedCrusaderr** [comment]
> Hi! The pull request was created to help newcomers achieve their first commit for Hacktoberfest. It was specifically created for @CapedCrusader. If we don't receive a response or if no longer interested in solving this issue within a couple of days, we will accept the first pull request.
> 
> 
> 
> to fix the issue you could remove the "/"
> 
> 
> 
> `<img src="/assets/images/github-mark-white.png" alt="GitHub">`
> 
> to
> 
>  `<img src="assets/images/github-mark-white.png" alt="GitHub">`
> 
> 
> 
> 
> 
> 
> 
> Also, I've created #42 so anyone can work on this new issue.

Sorry for the late reply @lcrojano  yes i would love to work on this issue😇
