### ISSUE TITLE
[enhancement ] Github Button Dark mode

### ISSUE THREAD

**Issue by lcrojano** [lcrojano/Giphy_Explorer#42]
Change icon and text to black, and background to #f9f9f9, only for dark mode.

![image](https://github.com/lcrojano/Giphy_Explorer/assets/5177737/10624005-0dc3-4615-bd0b-4d14c0c868d8)

to 

![image](https://github.com/lcrojano/Giphy_Explorer/assets/5177737/f9fdb89d-533c-4fb5-aef4-b9932b911736)

**Comment by dabhitapan** [comment]
@lcrojano assign it to me

**Comment by dabhitapan** [comment]
@lcrojano https://github.com/lcrojano/Giphy_Explorer/pull/44
