### ISSUE TITLE
refactor: Improve UI with [Modern UI Style] Design Guidelines

### ISSUE THREAD

**Issue by lcrojano** [lcrojano/Giphy_Explorer#52]
Issue 3: Improve UI with [Modern UI Style] Design Guidelines
Description:
Update the UI to follow modern design principles (name the style, e.g., Material Design, Fluent UI) with enhancements to colors, font sizing, and overall layout for a GIF website.

Acceptance Criteria:

Refine the color scheme for better visual appeal and accessibility.
Adjust font sizes and typography for better readability.
Ensure consistency in UI elements (buttons, modals, navigation).

**Comment by itsharshitrwt** [comment]
I want to work on this issue, plz assign :)
