### ISSUE TITLE
feat: Implement Husky, Commitizen, and Prettier for Contribution Standardization

### ISSUE THREAD

**Issue by lcrojano** [lcrojano/Giphy_Explorer#53]
**Description**
Set up **Husky**, **Commitizen**, **gitmoji**, **cz-customizable**, **commitlint**, and **Prettier ** to standardize code formatting and commit messages, ensuring consistency across contributions.

**Acceptance Criteria:**
Husky is configured for pre-commit and pre-push hooks.
Commitizen is set up for standardized commit messages using gitmoji.
Prettier is installed and configured for consistent code formatting.

**Integrate All Tools:**

Husky to manage hooks (e.g., run tests or linters before commits).
Commitizen and cz-customizable to standardize commit messages, possibly with gitmoji for visual clarity.
commitlint to enforce commit message rules, ensuring consistency.
Prettier to maintain a clean codebase.

**Comment by younusraza909** [comment]
can I help you on this?

**Comment by lcrojano** [comment]
@younusraza909 Sure, go ahead.

**Comment by lcrojano** [comment]
Hey @younusraza909, great progress on the PR! There are a few improvements we can make to ensure the workflow is fully automated and meets the expected behavior:

The idea is that when someone wants to make a commit, it should be rejected if it is not in the correct format. Additionally, to ensure the correct format, a guided commit formatter should be triggered. Before the commit is validated, the added code should be formatted with npx prettier, and all of this should be automated using Husky.

- [ ] Husky Hooks: Ensure the hooks (pre-commit, commit-msg) are correctly installed and enabled. 
- [ ] Commitizen: Ensure that Commitizen is properly integrated with cz-customizable or gitmoji, and verify that the config section in package.json is correctly pointing to your custom configuration.
- [ ] Scripts Execution: Make sure the necessary scripts (like commitizen or cz-customizable) are correctly added to the scripts section in package.json and are being triggered by Husky hooks.
- [ ] Prettier: Ensure Prettier is properly configured and formatted correctly in the codebase.  confirm Prettier runs as part of your pre-commit hook.
- [ ] Gitmoji and commitlint: Verify the integration between commitlint and gitmoji. 

Review these configurations in the PR and ensure dependencies are installed, hooks are activated, and everything is properly linked

These articles could be helpful: 
 
- [Setting Up Gitmoji in Commitizen, Commitlint, Conventional Changelog, and Semantic Release with… | by Jebarpg - Freedium](https://www.freedium.cfd/https://medium.com/@jebarpg/setting-up-gitmoji-in-commitizen-commitlint-conventional-changelog-and-semantic-release-with-ace3ac7cc850)
- [Add Commitlint, Commitizen, Standard Version, and Husky to SvelteKit Project - DEV Community](https://dev.to/davipon/add-commitint-commitizen-standard-version-and-husky-to-sveltekit-project-14pc)
- [How to set up Commitzen with Husky - DEV Community](https://dev.to/ricardo_borges/how-to-set-up-commitzen-with-husky-4a57)

**Comment by younusraza909** [comment]
Sorry for the inconvenience! I noticed that Husky has a .gitignore file, which prevented the config file from being pushed with the rest of the code. Let me make the necessary changes and push again

**Comment by younusraza909** [comment]
@lcrojano You can check the source code now
