### ISSUE TITLE
Make the website title (h1 tag) clickable to redirect to the home page

### ISSUE THREAD

**Issue by AdityaGahukar** [lcrojano/Giphy_Explorer#61]
### Description:
Currently, the title of the website, `<h1 id="logo">Giphy Search</h1>`, is not clickable. Users are unable to return to the home page by clicking on the title when navigating the website.

### Steps to Reproduce:
1. Go to the [Giphy Explorer](https://lcrojano.github.io/Giphy_Explorer/).
2. Perform a search for any GIF.
3. Try clicking on the website title ("Giphy Search") to return to the home page.

### Expected Behavior:
Clicking on the website's title (h1 tag) should redirect users back to the home page.

### Actual Behavior:
Clicking on the website's title does not currently perform any action.

### Proposed Solution:
- Wrap the `<h1>` element in an anchor (`<a>`) tag to make it clickable and link it to the home page URL.

```html
<a href="/">
  <h1 class="grow-2" id="logo">Giphy Search</h1>
</a>
```

### Request:
I request that this issue be assigned under Hacktoberfest and would appreciate any feedback on my proposed changes.

**Comment by lcrojano** [comment]
Suggested Improvements:
**Accessibility:** Ensure that the clickable title is accessible for screen readers and keyboard users. You could add aria-label to the anchor tag for screen readers.

**Styling Considerations:** Verify that the a tag styling does not interfere with the existing design. You may need to ensure that adding the anchor tag doesn't alter the look of the <h1>.
